import {
  PreviewIcon,
  GithubIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  CheckIcon,
  ChevronRightIcon,
  LinkedIn,
  Codepen,
  X,
  Instagram,
  Facebook,
  BurgerIcon,
  CloseIcon,
  StarIcon,
  MsgIcon,
  PhoneIcon,
  HomeIcon,
  ProjectsIcon,
  ServicesIcon,
  BlogIcon,
  ContactIcon,
  HardwareDiagnosticsIcon,
  SoftwareInstallationIcon,
  SystemOptimizationIcon,
  MalwareRemovalIcon,
  DataBackupIcon,
  TechnicalSupportIcon,
  GlobeIcon,
  JavaScriptIcon,
  NextjsIcon,
  NodejsIcon,
  ReactIcon,
  TailwindCSS,
  TypescriptIcon,
  FlutterIcon,
  FirebaseIcon,
  Earning,
  Likes,
  Star,
  Timer,
} from './icons'
import type { FC, SVGProps } from 'react'

export const iconMap: Record<string, FC<SVGProps<SVGSVGElement>>> = {
  // Tech icons
  javascript: JavaScriptIcon,
  typescript: TypescriptIcon,
  react: ReactIcon,
  nextjs: NextjsIcon,
  nodejs: NodejsIcon,
  tailwindcss: TailwindCSS,
  flutter: FlutterIcon,
  firebase: FirebaseIcon,

  // Support icons
  'hardware-diagnostics': HardwareDiagnosticsIcon,
  'software-installation': SoftwareInstallationIcon,
  'system-optimization': SystemOptimizationIcon,
  'malware-removal': MalwareRemovalIcon,
  'data-backup': DataBackupIcon,
  'technical-support': TechnicalSupportIcon,

  // Social icons
  github: GithubIcon,
  linkedin: LinkedIn,
  codepen: Codepen,
  x: X,
  instagram: Instagram,
  facebook: Facebook,

  // UI icons
  'preview': PreviewIcon,
  'arrow-left': ArrowLeftIcon,
  'arrow-right': ArrowRightIcon,
  'chevron-right': ChevronRightIcon,
  'check': CheckIcon,
  'burger': BurgerIcon,
  'close': CloseIcon,
  'star': StarIcon,
  'email': MsgIcon,
  'phone': PhoneIcon,
  'home': HomeIcon,
  'projects': ProjectsIcon,
  'services': ServicesIcon,
  'blog': BlogIcon,
  'contact': ContactIcon,
  'globe': GlobeIcon,
  'earning': Earning,
  'likes': Likes,
  'star-filled': Star,
  'timer': Timer,
}
